apiVersion: v1
kind: Service
metadata:
  name: edge-healer-metrics
  namespace: kube-system
spec:
  selector:
    app: edge-healer
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      nodePort: 30080  
  type: NodePort
