apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-spread
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-spread
  template:
    metadata:
      labels:
        app: busybox-spread
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: busybox-spread
              topologyKey: kubernetes.io/hostname
      containers:
      - name: bb
        image: busybox:1.36
        command: ["sh", "-c", "sleep 3600"]
        lifecycle:
          postStart:
            exec:
              # Emits timestamp immediately after container is created
              command:
                - sh
                - -c
                - |
                  echo "[POSTSTART] $(date +%FT%T)"
          preStop:
            exec:
              # Emits timestamp just before the container is killed
              command:
                - sh
                - -c
                - |
                  echo "[PRESTOP]  $(date +%FT%T)"
